// <auto-generated />
namespace PGCodeFirst.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class UserLastLoginAddedNickLimited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserLastLoginAddedNickLimited));
        
        string IMigrationMetadata.Id
        {
            get { return "201509161515037_UserLastLoginAddedNickLimited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
